import type { ProductSpec, ProductLine } from "./types";

export const PRODUCTS: Record<ProductLine, ProductSpec> = {
  R1: {
    id: "R1",
    name: "IPC-R1",
    segment: "Residential",
    voltage: "120/240V Split-Phase",
    phases: 1,
    maxAmps: 200,
    maxBranches: 40,
    features: ["NILM", "Matter API", "Home Assistant", "Class 10/20 Trip"],
  },
  "R1+": {
    id: "R1+",
    name: "IPC-R1+",
    segment: "Residential",
    voltage: "120/240V + DC Multiport",
    phases: 1,
    maxAmps: 400,
    maxBranches: 40,
    features: ["Solar/BMS Bus", "EV PWM", "Matter", "Virtual Subpanels"],
  },
  C1: {
    id: "C1",
    name: "IPC-C1",
    segment: "Commercial",
    voltage: "120/208V 3-Phase",
    phases: 3,
    maxAmps: 800,
    maxBranches: 60,
    features: ["Peak Demand Shave", "Phase Balance", "BACnet/Modbus"],
  },
  C2: {
    id: "C2",
    name: "IPC-C2",
    segment: "Commercial",
    voltage: "277/480V 3-Phase",
    phases: 3,
    maxAmps: 2000,
    maxBranches: 84,
    features: ["15-min Peak Cap", "BMS Gateway", "High SCCR 65kA"],
  },
  D1: {
    id: "D1",
    name: "IPC-D1",
    segment: "Data Center",
    voltage: "High-Density AC PDU",
    phases: 3,
    maxAmps: 1200,
    maxBranches: 84,
    features: ["Branch Telemetry", "N+1 Ready", "STS Integration"],
  },
  D2: {
    id: "D2",
    name: "IPC-D2",
    segment: "Data Center",
    voltage: "380V HVDC Core",
    phases: 1,
    maxAmps: 2000,
    maxBranches: 96,
    features: ["<1ms Failover", "Arc Suppression", "UPS Sync"],
  },
};

export const RESIDENTIAL_CIRCUITS = [
  { label: "Kitchen Range", ratingA: 40, category: "Kitchen", critical: false, shedCapable: true },
  { label: "HVAC Compressor", ratingA: 40, category: "HVAC", critical: false, shedCapable: true },
  { label: "EV Charger", ratingA: 50, category: "EV", critical: false, shedCapable: true },
  { label: "Water Heater", ratingA: 30, category: "Thermal", critical: false, shedCapable: true },
  { label: "Dryer", ratingA: 30, category: "Laundry", critical: false, shedCapable: true },
  { label: "Washer", ratingA: 20, category: "Laundry", critical: false, shedCapable: true },
  { label: "Refrigerator", ratingA: 20, category: "Kitchen", critical: true, shedCapable: false },
  { label: "Living Lights", ratingA: 15, category: "Lighting", critical: false, shedCapable: true },
  { label: "Bedroom Lights", ratingA: 15, category: "Lighting", critical: false, shedCapable: true },
  { label: "Office / Desk", ratingA: 20, category: "Office", critical: false, shedCapable: true },
  { label: "Garage / Tools", ratingA: 20, category: "Garage", critical: false, shedCapable: true },
  { label: "Pool Pump", ratingA: 20, category: "Outdoor", critical: false, shedCapable: true },
  { label: "Medical Outlet", ratingA: 20, category: "Critical", critical: true, shedCapable: false },
  { label: "Network Rack", ratingA: 15, category: "Critical", critical: true, shedCapable: false },
  { label: "Heat Pump Aux", ratingA: 30, category: "HVAC", critical: false, shedCapable: true },
  { label: "Dishwasher", ratingA: 20, category: "Kitchen", critical: false, shedCapable: true },
];

export const COMMERCIAL_CIRCUITS = [
  { label: "HVAC Stage 1", ratingA: 60, category: "HVAC", critical: false, shedCapable: true },
  { label: "HVAC Stage 2", ratingA: 60, category: "HVAC", critical: false, shedCapable: true },
  { label: "Warehouse Lights A", ratingA: 40, category: "Lighting", critical: false, shedCapable: true },
  { label: "Warehouse Lights B", ratingA: 40, category: "Lighting", critical: false, shedCapable: true },
  { label: "Production Line 1", ratingA: 100, category: "Process", critical: true, shedCapable: false },
  { label: "Production Line 2", ratingA: 100, category: "Process", critical: true, shedCapable: false },
  { label: "Compressor Bank", ratingA: 80, category: "Process", critical: false, shedCapable: true },
  { label: "Office Floor 1", ratingA: 40, category: "Office", critical: false, shedCapable: true },
  { label: "Office Floor 2", ratingA: 40, category: "Office", critical: false, shedCapable: true },
  { label: "Elevator Bank", ratingA: 60, category: "Vertical", critical: true, shedCapable: false },
  { label: "Server Closet", ratingA: 30, category: "IT", critical: true, shedCapable: false },
  { label: "Dock Doors", ratingA: 30, category: "Logistics", critical: false, shedCapable: true },
  { label: "Battery Charge", ratingA: 50, category: "Storage", critical: false, shedCapable: true },
  { label: "Parking EV Array", ratingA: 100, category: "EV", critical: false, shedCapable: true },
  { label: "Kitchen / Cafe", ratingA: 40, category: "Kitchen", critical: false, shedCapable: true },
  { label: "Emergency Egress", ratingA: 20, category: "Critical", critical: true, shedCapable: false },
];

export const DATACENTER_CIRCUITS = [
  { label: "Rack Row A1", ratingA: 60, category: "IT", critical: true, shedCapable: false },
  { label: "Rack Row A2", ratingA: 60, category: "IT", critical: true, shedCapable: false },
  { label: "Rack Row B1", ratingA: 60, category: "IT", critical: true, shedCapable: false },
  { label: "Rack Row B2", ratingA: 60, category: "IT", critical: true, shedCapable: false },
  { label: "Rack Row C1", ratingA: 60, category: "IT", critical: true, shedCapable: false },
  { label: "Rack Row C2", ratingA: 60, category: "IT", critical: true, shedCapable: false },
  { label: "CRAC Unit 1", ratingA: 80, category: "Cooling", critical: true, shedCapable: false },
  { label: "CRAC Unit 2", ratingA: 80, category: "Cooling", critical: true, shedCapable: false },
  { label: "CRAC Unit 3", ratingA: 80, category: "Cooling", critical: false, shedCapable: true },
  { label: "PDU A Feed", ratingA: 100, category: "Distribution", critical: true, shedCapable: false },
  { label: "PDU B Feed", ratingA: 100, category: "Distribution", critical: true, shedCapable: false },
  { label: "STS Primary", ratingA: 200, category: "STS", critical: true, shedCapable: false },
  { label: "STS Secondary", ratingA: 200, category: "STS", critical: true, shedCapable: false },
  { label: "Network Core", ratingA: 40, category: "Network", critical: true, shedCapable: false },
  { label: "Lighting / BMS", ratingA: 30, category: "Facility", critical: false, shedCapable: true },
  { label: "Spare / Test", ratingA: 40, category: "Spare", critical: false, shedCapable: true },
];

export const NILM_DEVICES = [
  { id: "hvac", name: "HVAC Compressor", category: "HVAC", baseW: 2800 },
  { id: "ev", name: "EV Inverter", category: "EV", baseW: 7200 },
  { id: "wh", name: "Water Heater", category: "Thermal", baseW: 4500 },
  { id: "fridge", name: "Refrigerator", category: "Kitchen", baseW: 180 },
  { id: "dryer", name: "Clothes Dryer", category: "Laundry", baseW: 5200 },
  { id: "washer", name: "Washing Machine", category: "Laundry", baseW: 600 },
  { id: "lights", name: "LED Lighting", category: "Lighting", baseW: 420 },
  { id: "oven", name: "Induction Range", category: "Kitchen", baseW: 3100 },
  { id: "pool", name: "Pool Pump", category: "Outdoor", baseW: 1400 },
  { id: "server", name: "Home Server", category: "IT", baseW: 220 },
  { id: "heatpump", name: "Heat Pump", category: "HVAC", baseW: 1900 },
  { id: "misc", name: "Misc Standby", category: "Standby", baseW: 95 },
];
